version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    restart: always
